const CONSTANTS = {
  ENVIRONMENT: process.env.ENVIRONMENT,
  CORS_ORIGIN: process.env.CORS_ORIGIN,
  BUCKET_NAME: process.env.BUCKET_NAME,
  SIGNED_URL_EXPIRE_SECONDS: 60 * 60,
  WEBSOCKET_API_ENDPOINT: process.env.WEBSOCKET_API_ENDPOINT,
};

module.exports = CONSTANTS;
